---
title: "recode_vrs"
author: "Dahham Alsoud"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{recode_vrs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Raison dՐtre
Although new pragmatic platforms  currently exist, great deal of research data is still being collected in `excel`, where it is easier to code variables in a `short form`. For example, birth date is commonly coded as "dob" instead of "Date of birth", which is the `publication form`. The same applies to the `levels` of varibles (as "F" and "M", which are both levels for the "Age" variables).

Recoding variables and their levels back to their publication form is an inevitable task during statistical analysis and reporting results. 

The function [recode_vrs()] help effortlessly transform collected data into a publication-ready format using a supplied `data dictionary`. Combining [recode_vrs()] with a `data dictionary` ensures `consistency` in recoding across all your analyses and publications as one could easily forget how a variable was encoded in a previous analysis or publication. 

